### ISSUE TITLE
feature: Make GrpcMessage a generic type.

### ISSUE THREAD

**Issue by dvabuzyarov** [ngx-grpc/protoc-gen-ng#12]
feature: Make GrpcMessage a generic type.
``` typescript
export interface GrpcMessage<T = unknown> {
  toObject(): T;
  toJSON(): T;
}
```

It will improve type safety. And also wold be a required step to message interfaces.
Generate an interface type for proto messages, so it could be used in serialisable environments like ngrx.

**Comment by smnbbrv** [comment]
Implemented at https://github.com/ngx-grpc/ngx-grpc
