### ISSUE TITLE
Testing Serialization

### ISSUE THREAD

**Issue by ropottnik** [ngx-grpc/protoc-gen-ng#16]
I might be missing something. But I couldn't find tests checking whether the generated classes actually serialize and deserialize correctly. In my view, that's actually a crucial point for reliability. 

Would it be appreciated if I added tests for that?

**Comment by smnbbrv** [comment]
Hi @ropottnik,

this would be very much appreciated! There is no special purpose not to test it. I did not create them in first place because partly it is covered by protobuf library, however it would be perfect to have it in place!

**Comment by ropottnik** [comment]
great! 
so my approach would be to test indirectly with web-grpc. 

procedure would be quite simple:
check if the binary that the ngx-grpc objects produce, when parsed from web-grpc produce an object with the same info. also vice versa.

the assumption is then that web-grpc is the truth which might be debatable. however, I have been working with it for over a year and found no inconsistency when interacting with a python server. also it will make the tests easily readable, as opposed to, say, comparing binary proto. with this we can highlight the exact field that might cause problems.

I already know that there is a problem in serializing the `google.protobuf.Struct` message which is why I started investigating in the first place.
