### ISSUE TITLE
Int64s

### ISSUE THREAD

**Issue by jfyne** [ngx-grpc/protoc-gen-ng#7]
I think int64s are not being handled correctly. At the moment as you know they are set to be a `number`

I have an ID `688240403127731887` described with an int64 field. When this arrives into the browser the attribute in the class is `688240403127731800`, notice the `00` on the end, which is the tell tale javascript incorrectly handling an int64.

I know Protobufjs uses https://github.com/dcodeIO/Long.js to handle these.

**Comment by smnbbrv** [comment]
yes, you are right. This is not yet implemented. The JS number limitation is int53...
